"""Launchpad Protocols Package"""

from .coinlist import COINLIST_FUNCTIONS
from .polkastarter import POLKASTARTER_FUNCTIONS
from .daomaker import DAOMAKER_FUNCTIONS
from .copper import COPPER_FUNCTIONS
from .pinksale import PINKSALE_FUNCTIONS
from .seedify import SEEDIFY_FUNCTIONS
from .gamestarter import GAMESTARTER_FUNCTIONS
from .bullperks import BULLPERKS_FUNCTIONS
from .gamefi import GAMEFI_FUNCTIONS

LAUNCHPAD_PROTOCOLS = {
    'COINLIST': COINLIST_FUNCTIONS,
    'POLKASTARTER': POLKASTARTER_FUNCTIONS,
    'DAOMAKER': DAOMAKER_FUNCTIONS,
    'COPPER': COPPER_FUNCTIONS,
    'PINKSALE': PINKSALE_FUNCTIONS,
    'SEEDIFY': SEEDIFY_FUNCTIONS,
    'GAMESTARTER': GAMESTARTER_FUNCTIONS,
    'BULLPERKS': BULLPERKS_FUNCTIONS,
    'GAMEFI': GAMEFI_FUNCTIONS
}