"""DEX Protocols Package"""

from .uniswap import UNISWAP_FUNCTIONS
from .sushiswap import SUSHISWAP_FUNCTIONS
from .curve import CURVE_FUNCTIONS
from .balancer import BALANCER_FUNCTIONS
from .pancakeswap import PANCAKESWAP_FUNCTIONS
from .trader_joe import TRADERJOE_FUNCTIONS
from .velodrome import VELODROME_FUNCTIONS
from .camelot import CAMELOT_FUNCTIONS
from .beethoven import BEETHOVEN_FUNCTIONS
from .maverick import MAVERICK_FUNCTIONS
from .hashflow import HASHFLOW_FUNCTIONS
from .dodo import DODO_FUNCTIONS
from .kyberswap import KYBERSWAP_FUNCTIONS
from .zyberswap import ZYBERSWAP_FUNCTIONS
from .chronos import CHRONOS_FUNCTIONS
from .ramses import RAMSES_FUNCTIONS
from .zapper import ZAPPER_FUNCTIONS
from .zerion import ZERION_FUNCTIONS
from .loopring import LOOPRING_FUNCTIONS
from .vulpefi import VULPEFI_FUNCTIONS
from .zeroex import ZEROEX_FUNCTIONS
from .paraswap import PARASWAP_FUNCTIONS
from .mixswap import MIXSWAP_FUNCTIONS
from .curve_dao import CURVE_DAO_FUNCTIONS

DEX_PROTOCOLS = {
    'UNISWAP': UNISWAP_FUNCTIONS,
    'SUSHISWAP': SUSHISWAP_FUNCTIONS,
    'CURVE': CURVE_FUNCTIONS,
    'BALANCER': BALANCER_FUNCTIONS,
    'PANCAKESWAP': PANCAKESWAP_FUNCTIONS,
    'TRADER_JOE': TRADERJOE_FUNCTIONS,
    'VELODROME': VELODROME_FUNCTIONS,
    'CAMELOT': CAMELOT_FUNCTIONS,
    'BEETHOVEN': BEETHOVEN_FUNCTIONS,
    'MAVERICK': MAVERICK_FUNCTIONS,
    'HASHFLOW': HASHFLOW_FUNCTIONS,
    'DODO': DODO_FUNCTIONS,
    'KYBERSWAP': KYBERSWAP_FUNCTIONS,
    'ZYBERSWAP': ZYBERSWAP_FUNCTIONS,
    'CHRONOS': CHRONOS_FUNCTIONS,
    'RAMSES': RAMSES_FUNCTIONS,
    'ZAPPER': ZAPPER_FUNCTIONS,
    'ZERION': ZERION_FUNCTIONS,
    'LOOPRING': LOOPRING_FUNCTIONS,
    'VULPEFI': VULPEFI_FUNCTIONS,
    'ZEROEX': ZEROEX_FUNCTIONS,
    'PARASWAP': PARASWAP_FUNCTIONS,
    'MIXSWAP': MIXSWAP_FUNCTIONS,
    'CURVE_DAO': CURVE_DAO_FUNCTIONS
}